title: Your Name
email: your.email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A research & data science portfolio site powered by GitHub Pages and Jekyll.
baseurl: "" 
url: "https://quciet.github.io" 
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
