title: Yutang
email: yutang.xiong@du.edu
description: >- # this means to ignore newlines until "baseurl:"
  A research & data science portfolio site powered by GitHub Pages and Jekyll.
baseurl: "" 
url: "https://quciet.github.io" 
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Yutang
  email: yutang.xiong@du.edu
  github: https://github.com/quciet
  linkedin: https://www.linkedin.com/in/yutang-xiong
